spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hangout?serverTimezone=Asia/Seoul
    username:
    password:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: localhost
    port: 6379

  config:
    import:
      - application-oauth.yml

application:
  security:
    jwt:
      secret-key: 6D5A7134743777217A25432A46294A404E635266556A586E3272357538782F41
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

# http url 괄호 허용
server:
  tomcat:
    relaxed-query-chars: '|,{,},[,]'